# Generated by Django 4.0.4 on 2022-05-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectCar', '0002_contact_us_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='date_created',
        ),
    ]
