# Generated by Django 4.0.4 on 2022-05-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectCar', '0005_contact_us_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='ContactUs',
        ),
    ]
