# Generated by Django 4.0.4 on 2022-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectCar', '0006_rename_contact_us_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
