# Generated by Django 4.0.4 on 2022-05-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectCar', '0007_alter_contactus_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='User_email',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='User_message',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='User_subject',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='last_name',
        ),
    ]
